# This is a basic workflow
name: CI

on:
  push:
    branches: 
    - main

jobs:
  
  my-testing:
    runs-on: ubuntu-latest
    steps:
      
      - uses: actions/checkout@v1
      
      - name: List current folder
        run: ls -la
      - name: GitHub Action for pytest
        uses: cclauss/GitHub-Action-for-pytest@master
        with:
          args: pytest lab1/zeroth.py lab1/first.py lab1/second.py